
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-12T22:05:01-0600",
 "dirty": true,
 "error": null,
 "full-revisionid": "7352888aeb478ca6ba69a4404e78e2bb7e7768cf",
 "version": "0.5.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
