VERSION_YEAR = 2023
VERSION_MONTH = int('07')
VERSION_DAY = int('13')
VERSION_HOUR = int('14')
VERSION_MINUTE = int('45')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202307131445
version_date = '2023/07/13 14:45'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
