"""
    Semp Write & Reader
    Version:v0.2.6 Beta
"""
BINARY_TRUE="binary_true_T_WriteBinary"
BINARY_FALSE="binary_false_F_OnlyWrite"
class Requester:
    def __init__(self, website: str = ...) -> None:
        self.websitelink = None
        ...

    def download(self, name: str = ..., binary=False) -> None:...

    def responseget(self) -> None:...

class SempWrite:
    def __init__(self,filename,encoding="utf-8") -> None:
        self.encoding = None
        self.name_filename = None
        ...

    def ReadAndDeleteAllWord(self,binary=BINARY_FALSE) -> None:...

    def ResponseAndAddFile(self,website) -> None:...

    def ResponseAndWriteFile(self,website) -> None:...

    def OnlyRead(self) -> None:...

    def OnlyWrite(self,text) -> None:...

    def OnlyAdd(self,text) -> None:...

    def CopyAnotherFileToThisFile(self,filename) -> None:...

    def config(self,filename=None,encoding=None) -> None:...

writer=SempWrite