"""
    SempCommand Alpha
    Version:a109
"""
EXIST_TRUE=True
EXIST_FALSE=False

class ModeError(Exception):
    def __init__(self, *args, **kwargs) -> None:...

class Commander:
    def __init__(self) -> None:...

    def RunCommand(self,command: str = ...,shell: bool = True) -> None:...

    def path_exist(self,path: str = ...) -> None:...

    def create_path(self,path:str = ...,parents:bool = False) -> None:...

    def path_is_dir(self,path: str = ...) -> None:...

    def path_is_file(self,path: str = ...) -> None:...

    def remove_file(self,path: str = ...) -> None:...

    def remove_directory(self,path: str = ...) -> None:...

    def file_size(self,path: str = ...) -> None:...

    def file_time(self,path: str = ...,mode: int = 1) -> None:...

    def rename(self,path: str = ...,new_name: str = ...) -> None:...

    def systemcommand(self,command: str = ...) -> None:...
