
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-09T22:27:12-0600",
 "dirty": true,
 "error": null,
 "full-revisionid": "d2d9b1b49e1b2dde1305ce8b3a982e5244eb4ba5",
 "version": "0.6.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
