
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-14T20:14:06+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "80003e1b290e3f3e3ff2630704e42d436999d7b7",
 "version": "0.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
