"""
    Koverse Data Platform (KDP) API

    The KDP API is a REST API that can be used to create, access, and update data in KDP Workspaces  # noqa: E501

    The version of the OpenAPI document: 4.69.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kdp_api
from kdp_api.model.audit_log_event_list import AuditLogEventList
globals()['AuditLogEventList'] = AuditLogEventList
from kdp_api.model.audit_log_paginator import AuditLogPaginator


class TestAuditLogPaginator(unittest.TestCase):
    """AuditLogPaginator unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuditLogPaginator(self):
        """Test AuditLogPaginator"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AuditLogPaginator()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
