"""
    Koverse Data Platform (KDP) API

    The KDP API is a REST API that can be used to create, access, and update data in KDP Workspaces  # noqa: E501

    The version of the OpenAPI document: 4.69.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kdp_api
from kdp_api.model.group import Group
globals()['Group'] = Group
from kdp_api.model.group_list import GroupList


class TestGroupList(unittest.TestCase):
    """GroupList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGroupList(self):
        """Test GroupList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GroupList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
