"""
    Koverse Data Platform (KDP) API

    The KDP API is a REST API that can be used to create, access, and update data in KDP Workspaces  # noqa: E501

    The version of the OpenAPI document: 4.69.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kdp_api
from kdp_api.model.delete_record_by_id_request import DeleteRecordByIdRequest


class TestDeleteRecordByIdRequest(unittest.TestCase):
    """DeleteRecordByIdRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeleteRecordByIdRequest(self):
        """Test DeleteRecordByIdRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DeleteRecordByIdRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
