# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class MixItemType(str, enum.Enum):
    AUDIO = "audio"
    VIDEO = "video"

    def visit(self, audio: typing.Callable[[], T_Result], video: typing.Callable[[], T_Result]) -> T_Result:
        if self is MixItemType.AUDIO:
            return audio()
        if self is MixItemType.VIDEO:
            return video()
