VERSION_YEAR = 2023
VERSION_MONTH = int('07')
VERSION_DAY = int('18')
VERSION_HOUR = int('02')
VERSION_MINUTE = int('57')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202307180257
version_date = '2023/07/18 02:57'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
