from setuptools import find_packages, setup   

setup(name='BIOecmpy',
    version='2.0',
    description='Automated construction of enzyme constraint models using ECMpy workflow',
    author='TIB BioDesign Center',
    url = 'https://github.com/A-runaaaa/ecmpy',
    license='MIT',
    packages=find_packages(),
    zip_safe=False,
    include_package_data=True,
    install_requires = [
        '  requests',
        '  pebble',  
        '  xlsxwriter',  
        '  Bio',   
        '  Require',  
        '  quest',   
        '  scikit-learn',  
        '  RDKit',  
        '  seaborn', 
        '  pubchempy',
        '  torch',
        '  ipykernel', 
        '  bioservices==1.10.4',
        '  pyprobar',
        '  xmltodict',
        ],
)