#!bin/env/python
import argparse
import os
import pandas as pd
import re

parser = argparse.ArgumentParser()

parser.add_argument("-i", dest="input", help="input file generated by running contact_diffs.py", required=True)
parser.add_argument("-o", dest="output", help="output file name", required=True)
args = parser.parse_args()

def compare_files(test_file):
    with open(test_file) as parsed_file:
        A_sites = []
        for line in parsed_file:
            #match = re.search(r'501',line)
            match = re.search(r'122|124|126|128|130|131|132|133|135|137|138|140|141|142|143|144|145|146|152|162|168|165|182|198|246|252|205',line)
            if match:
                print(line)
                A_sites.append(line)
    return A_sites

A_adj = compare_files(args.input)
#print(rbs_adj)
diff_df = pd.DataFrame(A_adj)
diff_df.to_csv(args.output)

